- link:
    ~/.local/share/applications/st.desktop: local/share/applications/st.desktop
    ~/.local/share/applications/Telconi.win.desktop: local/share/applications/Telconi.win.desktop
    ~/.local/share/applications/Winbox.desktop:  local/share/applications/Winbox.desktop

