- link:
    ~/.vimrc: vimrc
    ~/.vim/bundle: vim/bundle
    ~/.zshrc: zshrc
    ~/.ssh/config: ssh/config
    ~/.oh-my-zsh/custom/themes: oh-my-zsh/custom/themes
    ~/.config/polybar/scripts: config/polybar/scripts
    ~/.rc-function: rc-function
    ~/.config/sshmenu/config.json: config/sshmenu/config.json

- shell:
  - [pip3 install sshmenu]
