- defaults:
    link:
      force: true
      create: true
      relink: true

- link:
    ~/bin/rofi-logout: bin/rofi-logout

- clean: ['~']

- shell:
    - [git submodule update --init --recursive, Installing submodules]

